"""
Canonical component definitions for the BFD Dryer HMI.

SINGLE SOURCE OF TRUTH — the UMAS/Modbus poll loop, the REST command layer and
the CSV logger all import from here.

Reconciled 2026-06-15 to the FINAL loaded PLC program `BFD_final.smbp`
(generated by `make_final.py` in ~/projects/bfa-plc-cli).  The PLC is the source
of truth; this file conforms to it.  See HMI_CONTRACT.md and
docs/superpowers/specs/2026-06-15-bfa-hmi-final-plc-reconciliation-design.md.

Final-PLC contract (from make_final.py `ATV12_DRIVES` + the DOL/burner rungs +
gen_ladder.MANUAL_PARAMS first-scan defaults):

  Command word %MW0 — bit k (`%MW0:Xk`) = on/off request for the component with
  cmd_bit=k.  The PLC ANDs each command with the run-permit / safety / fan-airflow
  interlocks, so "commanded" is NOT the same as "running" on the final program
  (unlike the earlier %Q = %MW0:Xn build).  Running feedback comes from the drive
  status / process bits, not from %MW0 — but the final program does not yet mirror
  a per-component running word into %MW, so the HMI shows commanded state and we
  derive a coarse "running" from the safety/fault gates (see poll_loop).

  %MW0 command bits (audited against make_final.py 2026-06-15 — ALL MATCH):
    X0  hot_fan      (%M23 -> %Q0.0 plain coil)
    X1  disch_agi    (%Q0.1 plain coil)
    X2  spinner      (ATV320 %DRV3, slave 4, permit %M47)
    X3  agitator1    (ATV12  %DRV1, slave 2, permit %M45)
    X4  mill         (%Q0.4 DOL)
    X5  disch_conv   (%Q0.5 DOL)
    X6  load_conv    (%Q0.6 DOL)
    X7  brush        (%Q0.7 DOL)
    X8  shaker       (%Q0.8 DOL)
    X9  agitator2    (ATV12  %DRV2, slave 3, permit %M46)
    X10 trace_chain  (ATV12  %DRV0, slave 1, permit %M44)
    X11 burner       (%M25 -> %Q0.2/%Q0.3)
    (burner_high = %M28 -> %Q0.3 is AUTOMATIC; no %MW0 bit — status-only tile.)

  Drive speed setpoints — Hz, HMI writes (replaces the old %MW1-6 % scale):
    %MW40 spinner   %MW41 ag1   %MW42 ag2   %MW43 trace   %MW44 hot-fan
    NB: these are *Hz* (0-50), not 0-100 %.  The fan VSD runs at a fixed speed
    (10 V hardware bridge), so %MW44 is retained for display only.

  Temperatures — °C ×10, HMI reads directly (the temp-mirror rungs copy the
  TM3TI4 inputs %IW1.0-3 into %MW31-34 each scan):
    %MW31 burner-air   %MW32 product1   %MW33 product2   %MW34 exhaust
    (%MW30 hot-fan motor is NOT wired on the final program — reads 0.)

  Burner operator setpoints — °C ×10, HMI writes:
    %MW45 burner target (85.0)   %MW46 hysteresis band (2.0)
    %MW49 product scorch trip (92.0)
    SAFETY (NOT operator-settable from the HMI; first-scan only):
    %MW47 over-temp trip (98.0), %MW48 over-temp re-enable (95.0),
    %MW51 fire limit (120.0), %MW52 fire re-enable (110.0).

  Safety / faults — %M bits, HMI reads via UMAS func 0x24, object class 0x02
  (see umas_client.read_bits; descriptor confirmed from MEB captures 2026-06-15):
    %M4  safety-OK monitor  (mirrors %I0.13, active-HIGH = OK)
    %M20 FIRE-TRIP latch    %M21 OVER-TEMP latch    %M22 SCORCH latch
    %M23 hot-fan-on demand  (used for fan_proven status, not the command bit)

Speeds displayed = commanded (the Hz the HMI last wrote).  Actual-RPM feedback
via the ATV IOScanner read words (%IWN10x RFRD) is DEFERRED to phase 2.

Fields
------
id            : unique string key used in REST payloads and WS JSON
label         : human-readable label shown in the UI
kind          : 'vsd' | 'dol' | 'burner'
has_speed     : True if a speed setpoint register exists
cmd_bit       : bit index in %MW0 (command word) — 0-based
status_bit    : bit index used for fault/running mapping (= cmd_bit here)
speed_sp_reg  : %MW address of the Hz speed setpoint (None if not a speed drive)
speed_unit    : 'hz' | 'pct' — how the setpoint register is scaled when written
speed_act_reg : SIM-ONLY actual-speed %MW (modbus simulator path); None for live
fault_bit     : %M fault-latch address that faults THIS component (None if n/a)
manual        : False → indicator-only tile (no operator toggle)
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class Component:
    id: str
    label: str
    kind: str                            # 'vsd' | 'dol' | 'burner'
    has_speed: bool
    cmd_bit: int                         # bit in %MW0 (command word)
    status_bit: int                      # bit used for fault/running mapping
    speed_sp_reg: Optional[int] = None   # %MW address for the Hz setpoint
    speed_unit: str = "hz"               # 'hz' (drive Hz setpoint) | 'pct'
    speed_act_reg: Optional[int] = None  # SIM-ONLY actual-speed %MW (modbus sim)
    fault_bit: Optional[int] = None      # %M fault-latch addr that faults this component
    manual: bool = True                  # False → indicator only (no operator toggle)
    min_hz: float = 0.0                  # HMI minimum speed (drive LSP) — operator
                                         # cannot command below this; 0.0 = no floor
    speed_res_hz: float = 1.0            # Hz per setpoint-register count. 1.0 = the
                                         # register is whole-Hz (default contract);
                                         # 0.1 = tenths (finer steps, e.g. trace chain)


# ---------------------------------------------------------------------------
# %M fault-latch addresses (read via UMAS 0x24 object-class 0x02 = %M bit)
# ---------------------------------------------------------------------------
M_SAFETY_OK   = 4    # %M4  — mirrors %I0.13 (active-HIGH = safety engaged/OK)
M_FIRE_TRIP   = 20   # %M20 — ANY temp ≥ fire limit  → kills the fan
M_OVER_TEMP   = 21   # %M21 — ANY temp ≥ over-temp   → cuts burner
M_SCORCH      = 22   # %M22 — product temp ≥ scorch  → cuts burner
M_HOT_FAN_ON  = 23   # %M23 — hot-fan-on demand (fan_proven status source)

# All %M addresses the poll loop reads each cycle (one read_bits burst).
M_READ_ADDRS = [M_SAFETY_OK, M_FIRE_TRIP, M_OVER_TEMP, M_SCORCH, M_HOT_FAN_ON]

# Human-readable fault definitions, surfaced in the State JSON `faults` list.
# (bit -> (id, label, severity)). Severity: 'critical' (fire) | 'fault'.
FAULT_DEFS: dict[int, dict] = {
    M_FIRE_TRIP: {"id": "fire_trip",  "label": "FIRE TRIP — fan force-off",      "severity": "critical"},
    M_OVER_TEMP: {"id": "over_temp",  "label": "OVER-TEMP — burner cut",          "severity": "fault"},
    M_SCORCH:    {"id": "scorch",     "label": "PRODUCT SCORCH — burner cut",     "severity": "fault"},
}


# ---------------------------------------------------------------------------
# Component table — order preserved for WS/CSV consumers (do NOT reorder).
# cmd_bit values audited against make_final.py %MW0:X* 2026-06-15 (all match).
# fault_bit wires the burner-affecting trips to the burner tile; the fan tile
# gets the fire-trip (which force-stops the fan).
# ---------------------------------------------------------------------------
COMPONENTS: list[Component] = [
    # Hot fan — plain coil on the final program; %MW44 retained for display only.
    Component("hot_fan",     "Hot Fan",            "vsd",    True,   0,  0,
              speed_sp_reg=44, speed_unit="pct", fault_bit=M_FIRE_TRIP),

    # Discharge agitator — soft-start run/stop coil, no speed setpoint.
    Component("disch_agi",   "Discharge Agitator", "vsd",    False,  1,  1),

    # ATV drives on the Modbus IOScanner — Hz speed setpoints %MW40-43.
    # min_hz = the drive's provisioned low-speed (LSP) the HMI must not go below
    # (TC 10 Hz, Agitators 20 Hz; Spinner floored at 20 Hz per operator).
    Component("spinner",     "Spinner",            "vsd",    True,   2,  2,  speed_sp_reg=40, min_hz=20.0),
    Component("agitator1",   "Agitator 1",         "vsd",    True,   3,  3,  speed_sp_reg=41, min_hz=20.0),
    Component("agitator2",   "Agitator 2",         "vsd",    True,   9,  9,  speed_sp_reg=42, min_hz=20.0),
    Component("trace_chain", "Trace Chain",        "vsd",    True,  10, 10,  speed_sp_reg=43, min_hz=10.0,
              speed_res_hz=0.1),   # dwell-critical belt → 0.1 Hz fine steps (%MW43 in tenths)

    # DOL bank (Q0.4-Q0.8) — no speed.
    Component("mill",        "Mill",               "dol",    False,  4,  4),
    Component("disch_conv",  "Discharge Conveyor", "dol",    False,  5,  5),
    Component("load_conv",   "Loading Conveyor",   "dol",    False,  6,  6),
    Component("brush",       "Brush",              "dol",    False,  7,  7),
    Component("shaker",      "Shaker",             "dol",    False,  8,  8),

    # Burner — automatic (airflow + hysteresis + trips). Status-only tile.
    # Both over-temp and scorch latches cut the burner, so map both to the tile.
    Component("burner",      "Burner",             "burner", False, 11, 11,
              fault_bit=M_OVER_TEMP, manual=False),
    Component("burner_high", "Burner High",        "burner", False, 12, 12, manual=False),
]

# Lookup by id
COMPONENT_MAP: dict[str, Component] = {c.id: c for c in COMPONENTS}

# ---------------------------------------------------------------------------
# Register addresses
# ---------------------------------------------------------------------------

# Command word — %MW0; the PLC AND-gates each bit with the interlocks.
REG_CMD_WORD  = 0   # %MW0

# Temperature mirror base / map (°C ×10).  %MW30 (hot-fan motor) not wired → 0.
REG_TEMP_BASE = 30
TEMP_REGS = {
    "hotfan_motor": 30,   # NOT wired on the final program (reads 0)
    "burner":       31,   # burner-air PT100
    "product1":     32,
    "product2":     33,
    "exhaust":      34,
}

# Burner operator setpoints — match gen_ladder.MANUAL_PARAMS (the FINAL program's
# first-scan defaults):
#   %MW45 = burner air TARGET setpoint   (850 = 85.0 °C)
#   %MW46 = burner hysteresis band ±     (20 = 2.0 °C)
#   %MW49 = product scorch trip          (920 = 92.0 °C; Prod1/2 ≥ → burner OFF)
# SAFETY (NOT operator-settable from the HMI; first-scan only in the ladder):
#   %MW47 over-temp trip (98.0), %MW48 re-enable (95.0),
#   %MW51 fire limit (120.0), %MW52 re-enable (110.0).
REG_BURNER_SP    = 45  # %MW45 — burner air target setpoint
REG_BURNER_BAND  = 46  # %MW46 — burner hysteresis band ±
REG_PRODUCT_MAX  = 49  # %MW49 — product scorch trip → burner OFF

# Default setpoint values (°C) used to seed the sim register bank.
SP_DEFAULTS = {
    "burner_target": 85.0,
    "burner_band":   2.0,
    "product_max":   92.0,
}

# Key → register address mapping (for the REST setpoint handler).
SETPOINT_REG_MAP: dict[str, int] = {
    "burner_target": REG_BURNER_SP,
    "burner_band":   REG_BURNER_BAND,
    "product_max":   REG_PRODUCT_MAX,
}

# Speed-setpoint scaling.  The operator UI is a 0-100 % slider, but the FINAL PLC
# program reads the drive speed words %MW40-43 as Hz (0-50, AU 50 Hz grid).  So a
# 'hz'-unit speed write maps 0-100 % → 0-SPEED_HZ_MAX Hz (raw = round(pct/100 *
# SPEED_HZ_MAX)).  A 'pct'-unit write (hot-fan %MW44, display-only) stays 0-100.
SPEED_HZ_MAX = 50.0  # nominal drive frequency ceiling (Hz)


def speed_pct_to_raw(value_pct: float, unit: str, res_hz: float = 1.0) -> int:
    """Convert an operator 0-100 % speed to the raw %MW value for the setpoint
    register, honouring the register's unit + resolution.  'hz' → Hz scaled by
    res_hz (1.0 → whole-Hz count; 0.1 → tenths-of-Hz count, e.g. trace chain);
    'pct' → 0..100 (display-only). Always a non-negative integer."""
    pct = max(0.0, min(100.0, float(value_pct)))
    if unit == "hz":
        hz = pct / 100.0 * SPEED_HZ_MAX
        return int(round(hz / res_hz))
    return int(round(pct))

# fan_proven status source: the PLC's hot-fan-on demand bit %M23 (status, NOT the
# %MW0:X0 command bit).  Read via read_bits in the UMAS poll path.
# (Kept as a name the poll loop imports; the address lives in M_HOT_FAN_ON.)
BIT_FAN_PROVEN_M = M_HOT_FAN_ON

# ---------------------------------------------------------------------------
# SIMULATOR-ONLY register model (the in-process modbus sim in modbus_client.py)
# ---------------------------------------------------------------------------
# The sim keeps its OWN legacy register model: a running word at %MW20, a fault
# word at %MW21, and actual-speed words %MW22-27 that ramp toward setpoints.  The
# LIVE/UMAS path does NOT use any of these — it reads real %M safety/fault bits
# and shows commanded Hz.  These constants exist purely so the simulator and the
# modbus poll path keep working for dev/demo; they are NOT part of the live PLC
# contract and must not be relied on against hardware.
SIM_REG_RUNNING_WORD   = 20   # sim %MW20 — mirrored command bits after ~1 s
SIM_REG_FAULT_WORD     = 21   # sim %MW21 — always 0 (no faults simulated)
SIM_REG_SPEED_ACT_BASE = 22   # sim %MW22-27 — ramped actual speeds
SIM_BIT_FAN_PROVEN     = 13   # sim %MW20:X13 — mirrors hot-fan running
SIM_BIT_SAFETY_OK      = 14   # sim %MW20:X14 — always 1 (safety OK)

# Backward-compat aliases (the modbus sim path imports these names).  Live code
# must use the M_* / read_bits path instead.
REG_RUNNING_WORD   = SIM_REG_RUNNING_WORD
REG_FAULT_WORD     = SIM_REG_FAULT_WORD
REG_SPEED_ACT_BASE = SIM_REG_SPEED_ACT_BASE
BIT_FAN_PROVEN     = SIM_BIT_FAN_PROVEN
BIT_SAFETY_OK      = SIM_BIT_SAFETY_OK
